### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Crypt97** [SergeyDertan/SRegionProtector-pmmp#3]
Adding a feature that covers the whole world.

**for example:**
```
Worlds:

  world:

    # Keep players from getting hurt?
    Invincible: true

    # Keep players from editing the world?
    Break: false

    # Keep players from touching blocks?
    Place: false

  world2:

    # Keep players from getting hurt?
    Invincible: true

    # Keep players from editing the world?
    Break: false

    # Keep players from touching blocks?
    Place: false
```
